{
 "title": "Agoric Oracle Network Template",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "feed", "query": { "query": "label_values(feed)" } }
  ]
 },
 "panels": [
  {
   "title": "Config Thresholds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "config_heartbeat{feed=\"$feed\", group=\"Agoric Oracle Network\"}/60",
     "legendFormat": "Minutes"
    },
    {
     "expr": "config_threshold{feed=\"$feed\", group=\"Agoric Oracle Network\"}",
     "legendFormat": "Deviation threshold Percentage"
    }
   ]
  },
  { "title": "Pricing metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Last Observed Node Operator Price Submission",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "actual_price{feed=\"$feed\", group=\"Agoric Oracle Network\"}",
     "legendFormat": "Actual Value"
    },
    {
     "expr": "oracle_latest_value{feed=\"$feed\", group=\"Agoric Oracle Network\"}",
     "legendFormat": "{{oracleName}} - {{oracle}}"
    }
   ]
  },
  {
   "title": "Deviation from Actual Value (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracle_price_deviation{feed=\"$feed\", group=\"Agoric Oracle Network\"}",
     "legendFormat": "{{oracleName}} - {{oracle}}"
    }
   ]
  },
  {
   "title": "Actual value change in last 15mins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(actual_price{feed=\"$feed\", group=\"Agoric Oracle Network\"}[15m])",
     "legendFormat": "Actual Value"
    }
   ]
  },
  {
   "title": "Observed change in last 15mins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(oracle_latest_value{feed=\"$feed\", group=\"Agoric Oracle Network\"}[15m])",
     "legendFormat": "{{oracleName}} - {{oracle}}"
    }
   ]
  },
  { "title": "Round metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": " Time since Last on-chain value published (mins)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-max(oracle_last_observation{feed=\"$feed\", group=\"Agoric Oracle Network\"})/1000)/60"
    }
   ]
  },
  {
   "title": "Oracle Last Submission Age (mins)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-(oracle_last_observation{feed=\"$feed\", group=\"Agoric Oracle Network\"})/1000)/60",
     "legendFormat": "{{oracleName}} - {{oracle}}"
    }
   ]
  },
  {
   "title": " Time since last created round (mins)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-min(oracle_last_observation{feed=\"$feed\", group=\"Agoric Oracle Network\"})/1000)/60"
    }
   ]
  },
  {
   "title": " Time left for next update",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((min(oracle_last_observation{feed=\"$feed\", group=\"Agoric Oracle Network\"})/1000)+sum(config_heartbeat{feed=\"$feed\", group=\"Agoric Oracle Network\"})) - time()) / 60"
    }
   ]
  },
  {
   "title": "Rounds Created in the past 24 hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(oracle_rounds_created{feed=\"$feed\", group=\"Agoric Oracle Network\"}[24h])",
     "legendFormat": "{{oracleName}}"
    }
   ]
  },
  {
   "title": "Seconds taken for rounds to reach consensus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consensus_time_taken{feed=\"$feed\", group=\"Agoric Oracle Network\"}/1000",
     "legendFormat": "{{oracleName}} - {{oracle}}"
    }
   ]
  },
  {
   "title": "Oracle Last Submission round",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracle_last_round{feed=\"$feed\", group=\"Agoric Oracle Network\"}",
     "legendFormat": "{{oracleName}} - {{oracle}}"
    }
   ]
  },
  {
   "title": "Oracle Last Submission timestamp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "oracle_last_observation{feed=\"$feed\", group=\"Agoric Oracle Network\"}",
     "legendFormat": "{{oracleName}} - {{oracle}}"
    }
   ]
  },
  { "title": "Balances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Oracle Balances Days to 0",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(oracle_balance{brand=\"IST\", group=\"Agoric Oracle Network\"} - 100000) / (-1*delta(oracle_balance{brand=\"IST\", group=\"Agoric Oracle Network\"}[1d]))",
     "legendFormat": "{{oracleName}} - {{brand}}"
    }
   ]
  },
  {
   "title": "Oracle IST Balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracle_balance{brand=\"IST\", group=\"Agoric Oracle Network\"} / 1000000",
     "legendFormat": "{{oracleName}} - {{oracle}}"
    }
   ]
  }
 ]
}